### PR TITLE
Update DCTests.cs

### PR DESCRIPTION
**Pull request by chaojian-zhang**
- Fix typo

### CODE REVIEW

**Comment by svenboulanger** [comment]
Can you please sign your commit?

**Comment by chaojian-zhang** [comment]
Took me a while. Signed now.

**Comment by svenboulanger** [comment]
Hi, I can see that your new commits indeed signed now, but your first commit is still unsigned and so GitHub is giving me a "Merging is blocked" error.

You may want to squash your commits and then have that squashed commit be signed (may require a force push).

**Comment by svenboulanger** [comment]
It may not be worth the trouble for you, but I would like to keep all commits signed as a rule, sorry.

**Pull request closed without merging**
