### PR TITLE
Proper way of exposing configuration

### PR DESCRIPTION
**Pull request by marcin-golebiowski**
There is issue with current implementation. I'm unable to set initial conditions. The property where I can do it is set during Setup. There is no time when I could set initial conditions because the property is null.

### CODE REVIEW

**Comment by marcin-golebiowski** [comment]
@marcin-golebiowski  You are right about Configurations. I can but what is the purpose of the those properties ? I'm not sure what is a good solution.

**Comment by svenboulanger** [comment]
They were originally meant to provide a faster way of getting the configuration during runtime. But actually, we can just remove them and make behaviors cache them like they do with other behaviors and parameters.

**Comment by marcin-golebiowski** [comment]
@marcin-golebiowski 👍

**Comment by marcin-golebiowski** [comment]
@svenboulanger  Please proceed with that.

**Pull request closed without merging**
