### PR TITLE
Clean up the csproj files

### PR DESCRIPTION
**Pull request by hahschaa**
I saw that there were quite some shared properties in the `csproj` files, and moved those to the `Directory.Build.prop` and `-.target` files. Furthermore some NuGet packages were outdated, so I updated all of them ~~(meaning that the `NUnit` now need to use the legacy assertions, I can update all the assertions to the `Assert.That` in a follow up PR)~~.

I also updated the test project from .NET Framework 4.7.2 to .NET 8. But I can revert that if there is a good reason to stay on framework.

I don't know what the `<Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />` does in the `SpiceSharp` Project. Can that be removed?

### CODE REVIEW

**Comment by hahschaa** [comment]
Updating to the new NUnit constraints model was actually trivial using the `NUnit.Analyzers` package, so put that in this PR as well.

**Comment by svenboulanger** [comment]
> I don't know what the <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" /> does in the SpiceSharp Project. Can that be removed?

I think this is a remnant from when I was trying to use T4 instead of code generation. This should be fine to remove.

**Comment by hahschaa** [comment]
Okay, I removed that as well.

The only thing that I can see now to simplify is to use [GitInfo](https://github.com/devlooped/GitInfo) to automatically generate the version numbers based on the git tags. That way you never have to manually set the version numbers again. The only thing I'm not sure about is how that would work if you want to keep the versions of `SpiceSharp` and `SpiceSharpGenerator` separate, as it is now.

**Comment by svenboulanger** [comment]
I did not know that was possible. I'm definitely in favor.

I'd like the `SpiceSharp` library to be the only one following the tags. The generator is not modified often, and I don't want to start increasing the version of `SpiceSharp` if we ever make changes to the generator without changing the core project.

**Pull request merged**
